import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import FuncFormatter

# Set style for fancier plots
plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['figure.facecolor'] = 'white'
plt.rcParams['axes.facecolor'] = '#f8f9fa'
plt.rcParams['grid.alpha'] = 0.3
plt.rcParams['font.size'] = 11

# Custom formatter to avoid scientific notation
def log_format(value, pos):
    if value >= 1:
        return f'{int(value)}'
    else:
        return f'{value:.2g}'

# Read the data
data_32 = pd.read_csv('../data/data_32bit.csv')
data_64 = pd.read_csv('../data/data_64bit.csv')

# Filter data for varying polytopes (fixed vertices = 1000)
poly_32 = data_32[data_32['Vertices'] == 1000].sort_values('Polytopes')
poly_64 = data_64[data_64['Vertices'] == 1000].sort_values('Polytopes')

# Filter data for varying vertices (fixed polytopes = 1000)
vert_32 = data_32[data_32['Polytopes'] == 1000].sort_values('Vertices')
vert_64 = data_64[data_64['Polytopes'] == 1000].sort_values('Vertices')

# Plot 1: Polytopes vs Time (32-bit, log-regular)
plt.figure(figsize=(10, 6))
plt.plot(poly_32['Polytopes'], poly_32['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='GPU', color='#3498db')
plt.plot(poly_32['Polytopes'], poly_32['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='CPU', color='#2ecc71')
plt.xscale('log')
plt.xlabel('Number of Polytopes', fontsize=13, fontweight='bold')
plt.ylabel('Time (ms)', fontsize=13, fontweight='bold')
plt.title('32-bit: Execution Time vs Number of Polytopes (1000 vertices) [Log-X]', fontsize=14, fontweight='bold', pad=15)
plt.legend(fontsize=11, framealpha=0.95, edgecolor='black')
plt.grid(True, alpha=0.3, linestyle='--')
plt.tight_layout()
plt.savefig('../images/polytopes_vs_time_32bit_logx.png', dpi=150, bbox_inches='tight')
plt.close()

# Plot 2: Polytopes vs Time (32-bit, log-log)
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(poly_32['Polytopes'], poly_32['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='GPU', color='#3498db')
ax.plot(poly_32['Polytopes'], poly_32['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='CPU', color='#2ecc71')
ax.set_xscale('log')
ax.set_yscale('log')
ax.yaxis.set_major_formatter(FuncFormatter(log_format))
ax.set_xlabel('Number of Polytopes', fontsize=13, fontweight='bold')
ax.set_ylabel('Time (ms)', fontsize=13, fontweight='bold')
ax.set_title('32-bit: Execution Time vs Number of Polytopes (1000 vertices) [Log-Log]', fontsize=14, fontweight='bold', pad=15)
ax.legend(fontsize=11, framealpha=0.95, edgecolor='black')
ax.grid(True, alpha=0.3, linestyle='--', which='both')
plt.tight_layout()
plt.savefig('../images/polytopes_vs_time_32bit_loglog.png', dpi=150, bbox_inches='tight')
plt.close()

# Plot 3: Polytopes vs Time (64-bit, log-regular)
plt.figure(figsize=(10, 6))
plt.plot(poly_64['Polytopes'], poly_64['GPU_ms'], 'o-', linewidth=2.5, markersize=8, label='GPU', color='#e74c3c')
plt.plot(poly_64['Polytopes'], poly_64['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='GPU', color='#3498db')
plt.plot(poly_64['Polytopes'], poly_64['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='CPU', color='#2ecc71')
plt.xscale('log')
plt.xlabel('Number of Polytopes', fontsize=13, fontweight='bold')
plt.ylabel('Time (ms)', fontsize=13, fontweight='bold')
plt.title('64-bit: Execution Time vs Number of Polytopes (1000 vertices) [Log-X]', fontsize=14, fontweight='bold', pad=15)
plt.legend(fontsize=11, framealpha=0.95, edgecolor='black')
plt.grid(True, alpha=0.3, linestyle='--')
plt.tight_layout()
plt.savefig('../images/polytopes_vs_time_64bit_logx.png', dpi=150, bbox_inches='tight')
plt.close()

# Plot 4: Polytopes vs Time (64-bit, log-log)
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(poly_64['Polytopes'], poly_64['GPU_ms'], 'o-', linewidth=2.5, markersize=8, label='GPU', color='#e74c3c')
ax.plot(poly_64['Polytopes'], poly_64['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='GPU', color='#3498db')
ax.plot(poly_64['Polytopes'], poly_64['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='CPU', color='#2ecc71')
ax.set_xscale('log')
ax.set_yscale('log')
ax.yaxis.set_major_formatter(FuncFormatter(log_format))
ax.set_xlabel('Number of Polytopes', fontsize=13, fontweight='bold')
ax.set_ylabel('Time (ms)', fontsize=13, fontweight='bold')
ax.set_title('64-bit: Execution Time vs Number of Polytopes (1000 vertices) [Log-Log]', fontsize=14, fontweight='bold', pad=15)
ax.legend(fontsize=11, framealpha=0.95, edgecolor='black')
ax.grid(True, alpha=0.3, linestyle='--', which='both')
plt.tight_layout()
plt.savefig('../images/polytopes_vs_time_64bit_loglog.png', dpi=150, bbox_inches='tight')
plt.close()

# Plot 5: Vertices vs Time (32-bit, log-regular)
plt.figure(figsize=(10, 6))
plt.plot(vert_32['Vertices'], vert_32['GPU_ms'], 'o-', linewidth=2.5, markersize=8, label='GPU', color='#e74c3c')
plt.plot(vert_32['Vertices'], vert_32['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='GPU', color='#3498db')
plt.plot(vert_32['Vertices'], vert_32['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='CPU', color='#2ecc71')
plt.xscale('log')
plt.xlabel('Number of Vertices', fontsize=13, fontweight='bold')
plt.ylabel('Time (ms)', fontsize=13, fontweight='bold')
plt.title('32-bit: Execution Time vs Number of Vertices (1000 polytopes) [Log-X]', fontsize=14, fontweight='bold', pad=15)
plt.legend(fontsize=11, framealpha=0.95, edgecolor='black')
plt.grid(True, alpha=0.3, linestyle='--')
plt.tight_layout()
plt.savefig('../images/vertices_vs_time_32bit_logx.png', dpi=150, bbox_inches='tight')
plt.close()

# Plot 6: Vertices vs Time (32-bit, log-log)
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(vert_32['Vertices'], vert_32['GPU_ms'], 'o-', linewidth=2.5, markersize=8, label='GPU', color='#e74c3c')
ax.plot(vert_32['Vertices'], vert_32['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='GPU', color='#3498db')
ax.plot(vert_32['Vertices'], vert_32['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='CPU', color='#2ecc71')
ax.set_xscale('log')
ax.set_yscale('log')
ax.yaxis.set_major_formatter(FuncFormatter(log_format))
ax.set_xlabel('Number of Vertices', fontsize=13, fontweight='bold')
ax.set_ylabel('Time (ms)', fontsize=13, fontweight='bold')
ax.set_title('32-bit: Execution Time vs Number of Vertices (1000 polytopes) [Log-Log]', fontsize=14, fontweight='bold', pad=15)
ax.legend(fontsize=11, framealpha=0.95, edgecolor='black')
ax.grid(True, alpha=0.3, linestyle='--', which='both')
plt.tight_layout()
plt.savefig('../images/vertices_vs_time_32bit_loglog.png', dpi=150, bbox_inches='tight')
plt.close()

# Plot 7: Vertices vs Time (64-bit, log-regular)
plt.figure(figsize=(10, 6))
plt.plot(vert_64['Vertices'], vert_64['GPU_ms'], 'o-', linewidth=2.5, markersize=8, label='GPU', color='#e74c3c')
plt.plot(vert_64['Vertices'], vert_64['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='GPU', color='#3498db')
plt.plot(vert_64['Vertices'], vert_64['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='CPU', color='#2ecc71')
plt.xscale('log')
plt.xlabel('Number of Vertices', fontsize=13, fontweight='bold')
plt.ylabel('Time (ms)', fontsize=13, fontweight='bold')
plt.title('64-bit: Execution Time vs Number of Vertices (1000 polytopes) [Log-X]', fontsize=14, fontweight='bold', pad=15)
plt.legend(fontsize=11, framealpha=0.95, edgecolor='black')
plt.grid(True, alpha=0.3, linestyle='--')
plt.tight_layout()
plt.savefig('../images/vertices_vs_time_64bit_logx.png', dpi=150, bbox_inches='tight')
plt.close()

# Plot 8: Vertices vs Time (64-bit, log-log)
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(vert_64['Vertices'], vert_64['GPU_ms'], 'o-', linewidth=2.5, markersize=8, label='GPU', color='#e74c3c')
ax.plot(vert_64['Vertices'], vert_64['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='GPU', color='#3498db')
ax.plot(vert_64['Vertices'], vert_64['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='CPU', color='#2ecc71')
ax.set_xscale('log')
ax.set_yscale('log')
ax.yaxis.set_major_formatter(FuncFormatter(log_format))
ax.set_xlabel('Number of Vertices', fontsize=13, fontweight='bold')
ax.set_ylabel('Time (ms)', fontsize=13, fontweight='bold')
ax.set_title('64-bit: Execution Time vs Number of Vertices (1000 polytopes) [Log-Log]', fontsize=14, fontweight='bold', pad=15)
ax.legend(fontsize=11, framealpha=0.95, edgecolor='black')
ax.grid(True, alpha=0.3, linestyle='--', which='both')
plt.tight_layout()
plt.savefig('../images/vertices_vs_time_64bit_loglog.png', dpi=150, bbox_inches='tight')
plt.close()

# Plot 9: Polytopes vs Time (both precisions, log-log)
fig, ax = plt.subplots(figsize=(12, 6))
ax.plot(poly_32['Polytopes'], poly_32['GPU_ms'], 'o-', linewidth=2.5, markersize=8, label='32-bit GPU', color='#e74c3c')
ax.plot(poly_32['Polytopes'], poly_32['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='32-bit GPU', color='#3498db')
ax.plot(poly_32['Polytopes'], poly_32['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='32-bit CPU', color='#2ecc71')
ax.plot(poly_64['Polytopes'], poly_64['GPU_ms'], 'o--', linewidth=2, markersize=8, label='64-bit GPU', color='#e74c3c', alpha=0.6)
ax.plot(poly_64['Polytopes'], poly_64['GPU_ms'], 's--', linewidth=2, markersize=8, label='64-bit GPU', color='#3498db', alpha=0.6)
ax.plot(poly_64['Polytopes'], poly_64['CPU_ms'], 'D--', linewidth=2, markersize=7, label='64-bit CPU', color='#2ecc71', alpha=0.6)
ax.set_xscale('log')
ax.set_yscale('log')
ax.yaxis.set_major_formatter(FuncFormatter(log_format))
ax.set_xlabel('Number of Polytopes', fontsize=13, fontweight='bold')
ax.set_ylabel('Time (ms)', fontsize=13, fontweight='bold')
ax.set_title('Execution Time vs Number of Polytopes - 32-bit vs 64-bit (1000 vertices) [Log-Log]', fontsize=14, fontweight='bold', pad=15)
ax.legend(fontsize=10, framealpha=0.95, edgecolor='black', ncol=2)
ax.grid(True, alpha=0.3, linestyle='--', which='both')
plt.tight_layout()
plt.savefig('../images/polytopes_vs_time_both_loglog.png', dpi=150, bbox_inches='tight')
plt.close()

# Plot 10: Vertices vs Time (both precisions, log-log)
fig, ax = plt.subplots(figsize=(12, 6))
ax.plot(vert_32['Vertices'], vert_32['GPU_ms'], 'o-', linewidth=2.5, markersize=8, label='32-bit GPU', color='#e74c3c')
ax.plot(vert_32['Vertices'], vert_32['GPU_ms'], 's-', linewidth=2.5, markersize=8, label='32-bit GPU', color='#3498db')
ax.plot(vert_32['Vertices'], vert_32['CPU_ms'], 'D-', linewidth=2.5, markersize=7, label='32-bit CPU', color='#2ecc71')
ax.plot(vert_64['Vertices'], vert_64['GPU_ms'], 'o--', linewidth=2, markersize=8, label='64-bit GPU', color='#e74c3c', alpha=0.6)
ax.plot(vert_64['Vertices'], vert_64['GPU_ms'], 's--', linewidth=2, markersize=8, label='64-bit GPU', color='#3498db', alpha=0.6)
ax.plot(vert_64['Vertices'], vert_64['CPU_ms'], 'D--', linewidth=2, markersize=7, label='64-bit CPU', color='#2ecc71', alpha=0.6)
ax.set_xscale('log')
ax.set_yscale('log')
ax.yaxis.set_major_formatter(FuncFormatter(log_format))
ax.set_xlabel('Number of Vertices', fontsize=13, fontweight='bold')
ax.set_ylabel('Time (ms)', fontsize=13, fontweight='bold')
ax.set_title('Execution Time vs Number of Vertices - 32-bit vs 64-bit (1000 polytopes) [Log-Log]', fontsize=14, fontweight='bold', pad=15)
ax.legend(fontsize=10, framealpha=0.95, edgecolor='black', ncol=2)
ax.grid(True, alpha=0.3, linestyle='--', which='both')
plt.tight_layout()
plt.savefig('../images/vertices_vs_time_both_loglog.png', dpi=150, bbox_inches='tight')
plt.close()

print("All plots generated successfully!")
print("Generated 10 plots:")
print("  - 4 polytopes vs time plots (32-bit and 64-bit, log-x and log-log)")
print("  - 4 vertices vs time plots (32-bit and 64-bit, log-x and log-log)")
print("  - 2 combined precision plots (polytopes and vertices, log-log)")
